import "./globals.css";
import type { Metadata } from "next";
import "simplebar-react/dist/simplebar.min.css";
import "@rainbow-me/rainbowkit/styles.css";
import { Providers } from "@/app/providers";

export const metadata: Metadata = {
  title: "Hello Web3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
